function createfigure1(ymatrix1, XMatrix1, DMatrix1)
%CREATEFIGURE(YMATRIX1, XMATRIX1, DMATRIX1)
%  YMATRIX1:  bar matrix data
%  XMATRIX1:  errorbar x matrix data
%  DMATRIX1:  errorbar delta matrix data

%  Auto-generated by MATLAB on 20-May-2020 00:25:08

% Create figure
figure('Name','Figure');

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1);
set(bar1(8),'DisplayName','1Hz');
set(bar1(7),'DisplayName','2Hz');
set(bar1(6),'DisplayName','5Hz');
set(bar1(5),'DisplayName','10Hz');
set(bar1(4),'DisplayName','PDR_MEAN(:,1)');
set(bar1(3),'DisplayName','PDR_MEAN(:,2)');
set(bar1(2),'DisplayName','PDR_MEAN(:,3)');
set(bar1(1),'DisplayName','PDR_MEAN(:,4)');

% Create multiple error bars using matrix input to errorbar
errorbar(XMatrix1,ymatrix1,DMatrix1,'Marker','o','LineStyle','none',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('Densidad');

% Create title
title('PDR para diferentes densidades y tasa de TX');

% Create ylabel
ylabel('% PDR');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[1 2 3 4]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast');

