
#
# This makefile was generated with the following command:
# /home/ayanez/omnetpp-5.1.1/bin/opp_runall -j8 -b1 ../../CA_System -m -u Cmdenv -c Ped_Crossing-OnStreet-200bytes -n ../../../simulations:../..:../../../../omnetpp-5.1.1/samples/VRU/inet/src:../../../../omnetpp-5.1.1/samples/VRU/inet/examples:../../../../omnetpp-5.1.1/samples/VRU/inet/tutorials:../../../../omnetpp-5.1.1/samples/VRU/inet/showcases:../../../../Veins_Pedestrian/examples/veins:../../../../Veins_Pedestrian/src/veins:../../../../Veins_Pedestrian/subprojects/veins_inet/src/veins_inet:../../../../Veins_Pedestrian/subprojects/veins_inet/examples/veins_inet --image-path=../../../../omnetpp-5.1.1/samples/VRU/inet/images:../../../../Veins_Pedestrian/images -l ../../../../omnetpp-5.1.1/samples/VRU/inet/src/INET -l ../../../../Veins_Pedestrian/src/veins -l ../../../../Veins_Pedestrian/subprojects/veins_inet/src/veins_inet omnetpp2.ini
#

SIMULATIONCMD = ../../CA_System -m -u Cmdenv -c Ped_Crossing-OnStreet-200bytes -n ../../../simulations:../..:../../../../omnetpp-5.1.1/samples/VRU/inet/src:../../../../omnetpp-5.1.1/samples/VRU/inet/examples:../../../../omnetpp-5.1.1/samples/VRU/inet/tutorials:../../../../omnetpp-5.1.1/samples/VRU/inet/showcases:../../../../Veins_Pedestrian/examples/veins:../../../../Veins_Pedestrian/src/veins:../../../../Veins_Pedestrian/subprojects/veins_inet/src/veins_inet:../../../../Veins_Pedestrian/subprojects/veins_inet/examples/veins_inet --image-path=../../../../omnetpp-5.1.1/samples/VRU/inet/images:../../../../Veins_Pedestrian/images -l ../../../../omnetpp-5.1.1/samples/VRU/inet/src/INET -l ../../../../Veins_Pedestrian/src/veins -l ../../../../Veins_Pedestrian/subprojects/veins_inet/src/veins_inet omnetpp2.ini -s --cmdenv-redirect-output=true
TARGETS =  run0 run1 run2 run3 run4 run5 run6 run7 run8 run9 run10 run11 run12 run13 run14 run15 run16 run17 run18 run19 run20 run21 run22 run23 run24 run25 run26 run27 run28 run29 run30 run31 run32 run33 run34 run35 run36 run37 run38 run39 run40 run41 run42 run43 run44 run45 run46 run47 run48 run49 run50 run51 run52 run53 run54 run55 run56 run57 run58 run59 run60 run61 run62 run63 run64 run65 run66 run67 run68 run69 run70 run71 run72 run73 run74 run75 run76 run77 run78 run79

.PHONY: $(TARGETS)

all: $(TARGETS)
	@echo All runs completed.

run0:
	$(SIMULATIONCMD) -r 0

run1:
	$(SIMULATIONCMD) -r 1

run2:
	$(SIMULATIONCMD) -r 2

run3:
	$(SIMULATIONCMD) -r 3

run4:
	$(SIMULATIONCMD) -r 4

run5:
	$(SIMULATIONCMD) -r 5

run6:
	$(SIMULATIONCMD) -r 6

run7:
	$(SIMULATIONCMD) -r 7

run8:
	$(SIMULATIONCMD) -r 8

run9:
	$(SIMULATIONCMD) -r 9

run10:
	$(SIMULATIONCMD) -r 10

run11:
	$(SIMULATIONCMD) -r 11

run12:
	$(SIMULATIONCMD) -r 12

run13:
	$(SIMULATIONCMD) -r 13

run14:
	$(SIMULATIONCMD) -r 14

run15:
	$(SIMULATIONCMD) -r 15

run16:
	$(SIMULATIONCMD) -r 16

run17:
	$(SIMULATIONCMD) -r 17

run18:
	$(SIMULATIONCMD) -r 18

run19:
	$(SIMULATIONCMD) -r 19

run20:
	$(SIMULATIONCMD) -r 20

run21:
	$(SIMULATIONCMD) -r 21

run22:
	$(SIMULATIONCMD) -r 22

run23:
	$(SIMULATIONCMD) -r 23

run24:
	$(SIMULATIONCMD) -r 24

run25:
	$(SIMULATIONCMD) -r 25

run26:
	$(SIMULATIONCMD) -r 26

run27:
	$(SIMULATIONCMD) -r 27

run28:
	$(SIMULATIONCMD) -r 28

run29:
	$(SIMULATIONCMD) -r 29

run30:
	$(SIMULATIONCMD) -r 30

run31:
	$(SIMULATIONCMD) -r 31

run32:
	$(SIMULATIONCMD) -r 32

run33:
	$(SIMULATIONCMD) -r 33

run34:
	$(SIMULATIONCMD) -r 34

run35:
	$(SIMULATIONCMD) -r 35

run36:
	$(SIMULATIONCMD) -r 36

run37:
	$(SIMULATIONCMD) -r 37

run38:
	$(SIMULATIONCMD) -r 38

run39:
	$(SIMULATIONCMD) -r 39

run40:
	$(SIMULATIONCMD) -r 40

run41:
	$(SIMULATIONCMD) -r 41

run42:
	$(SIMULATIONCMD) -r 42

run43:
	$(SIMULATIONCMD) -r 43

run44:
	$(SIMULATIONCMD) -r 44

run45:
	$(SIMULATIONCMD) -r 45

run46:
	$(SIMULATIONCMD) -r 46

run47:
	$(SIMULATIONCMD) -r 47

run48:
	$(SIMULATIONCMD) -r 48

run49:
	$(SIMULATIONCMD) -r 49

run50:
	$(SIMULATIONCMD) -r 50

run51:
	$(SIMULATIONCMD) -r 51

run52:
	$(SIMULATIONCMD) -r 52

run53:
	$(SIMULATIONCMD) -r 53

run54:
	$(SIMULATIONCMD) -r 54

run55:
	$(SIMULATIONCMD) -r 55

run56:
	$(SIMULATIONCMD) -r 56

run57:
	$(SIMULATIONCMD) -r 57

run58:
	$(SIMULATIONCMD) -r 58

run59:
	$(SIMULATIONCMD) -r 59

run60:
	$(SIMULATIONCMD) -r 60

run61:
	$(SIMULATIONCMD) -r 61

run62:
	$(SIMULATIONCMD) -r 62

run63:
	$(SIMULATIONCMD) -r 63

run64:
	$(SIMULATIONCMD) -r 64

run65:
	$(SIMULATIONCMD) -r 65

run66:
	$(SIMULATIONCMD) -r 66

run67:
	$(SIMULATIONCMD) -r 67

run68:
	$(SIMULATIONCMD) -r 68

run69:
	$(SIMULATIONCMD) -r 69

run70:
	$(SIMULATIONCMD) -r 70

run71:
	$(SIMULATIONCMD) -r 71

run72:
	$(SIMULATIONCMD) -r 72

run73:
	$(SIMULATIONCMD) -r 73

run74:
	$(SIMULATIONCMD) -r 74

run75:
	$(SIMULATIONCMD) -r 75

run76:
	$(SIMULATIONCMD) -r 76

run77:
	$(SIMULATIONCMD) -r 77

run78:
	$(SIMULATIONCMD) -r 78

run79:
	$(SIMULATIONCMD) -r 79


