//
// Generated file, do not edit! Created by nedtool 5.1 from modules/messages/CBR_calc.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CBR_CALC_M_H
#define __CBR_CALC_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>modules/messages/CBR_calc.msg:26</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CBR_calc extends WaveShortMessage
 * {
 * }
 * </pre>
 */
class CBR_calc : public ::WaveShortMessage
{
  protected:

  private:
    void copy(const CBR_calc& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CBR_calc&);

  public:
    CBR_calc(const char *name=nullptr, short kind=0);
    CBR_calc(const CBR_calc& other);
    virtual ~CBR_calc();
    CBR_calc& operator=(const CBR_calc& other);
    virtual CBR_calc *dup() const override {return new CBR_calc(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CBR_calc& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CBR_calc& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CBR_CALC_M_H

